"""initial

Revision ID: initial
Revises: 
Create Date: 2025-07-24 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('military_offices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('district', sa.String(length=100), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('chief_phone', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('mac_address', sa.String(length=17), nullable=True),
        sa.Column('military_office_id', sa.Integer(), nullable=True),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.ForeignKeyConstraint(['military_office_id'], ['military_offices.id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_military_office_id', 'users', ['military_office_id'], unique=False)
    op.create_table('alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('type', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('military_office_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['military_office_id'], ['military_offices.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('priority BETWEEN 1 AND 5', name='priority_check')
    )
    op.create_index('idx_alerts_military_office_id', 'alerts', ['military_office_id'], unique=False)
    op.create_index('idx_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_table('alert_statuses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('alert_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('received_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('accepted_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('ready_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('total_time', sa.Interval(), sa.Computed('(ready_at - received_at)', persisted=True), nullable=True),
        sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_statuses_alert_id', 'alert_statuses', ['alert_id'], unique=False)
    op.create_table('events_ps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=True),
        sa.Column('source', sa.String(length=100), nullable=True),
        sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('military_office_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['military_office_id'], ['military_offices.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_ps_military_office_id', 'events_ps', ['military_office_id'], unique=False)
    op.create_table('employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('rank', sa.String(length=50), nullable=True),
        sa.Column('position', sa.String(length=100), nullable=True),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('telegram_id', sa.String(length=50), nullable=True),
        sa.Column('military_office_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['military_office_id'], ['military_offices.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employees_military_office_id', 'employees', ['military_office_id'], unique=False)
    op.create_table('conscripts',
        sa.Column('iin', sa.String(length=12), nullable=False),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('photo_url', sa.String(length=255), nullable=True),
        sa.Column('added_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('iin')
    )
    op.create_table('requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conscript_iin', sa.String(length=12), nullable=True),
        sa.Column('type', sa.String(length=50), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('escort_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['conscript_iin'], ['conscripts.iin'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['escort_id'], ['employees.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_requests_conscript_iin', 'requests', ['conscript_iin'], unique=False)
    op.create_table('devices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('login', sa.String(length=50), nullable=True),
        sa.Column('password', sa.String(length=100), nullable=True),
        sa.Column('military_office_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['military_office_id'], ['military_offices.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_devices_military_office_id', 'devices', ['military_office_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_devices_military_office_id', table_name='devices')
    op.drop_table('devices')
    op.drop_index('idx_requests_conscript_iin', table_name='requests')
    op.drop_table('requests')
    op.drop_table('conscripts')
    op.drop_index('idx_employees_military_office_id', table_name='employees')
    op.drop_table('employees')
    op.drop_index('idx_events_ps_military_office_id', table_name='events_ps')
    op.drop_table('events_ps')
    op.drop_index('idx_alert_statuses_alert_id', table_name='alert_statuses')
    op.drop_table('alert_statuses')
    op.drop_index('idx_alerts_created_at', table_name='alerts')
    op.drop_index('idx_alerts_military_office_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_users_military_office_id', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_table('users')
    op.drop_table('military_offices')
    op.drop_table('roles')
    # ### end Alembic commands ###